version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "@python/tzdata-maintainers"
    groups:
      actions:
        patterns:
          - "*"